# Create GitHub Action Repository Variables for your version of the application:
#   FOD_URL                     - FoD Portal URL for your tenant (e.g. https://ams.fortify.com)
#   FOD_DEFAULT_OWNER           - The user id of the Application Owner (only needed if an application does not already exist)
#   FOD_DEFAULT_ASSESSMENT_TYPE - The default Assessment Type to use, e.g. "Static Assessment"
#   FOD_DEFAULT_PARENT_RELEASE  - The name of the parent release to copy from, e.g. "main"
# Create GitHub Action Secrets for your version of the application:
#   FOD_CLIENT_ID should be an API Key obtained from your FoD tenant.
#   FOD_CLIENT_SECRET should be the secret for the API Key obtained for your FoD tenant.
# Helpful hints:
#   API Key credentials can be obtained from your FoD tenant, under Administration -> Settings -> API
#   It is recommended to create credentials with 'Security Lead' Role selected.
#   "Automated Audit preference" should be configured for the release's Static Scan Settings.
name: OpenText Core Application Security Scan

# Set the permissions for the GITHUB_TOKEN to allow the workflow to read repository contents, write security events, and write pull request comments. This is necessary for the workflow to function properly, as it needs to access the codebase for scanning, report security findings, and comment on pull requests with the results.
permissions:
  contents: read
  security-events: write
  pull-requests: write

on:
  push:
    branches: [ main, feature/**, bugfix/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fortify-ast-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties','**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew || true

      #
      # See: https://fortify.github.io/fcli/v3/ci/github/v3.0.x/ast-action-fod.html
      #
      - name: Run FoD SAST and SCA Scan
        timeout-minutes: 360
        uses: fortify/github-action@v3
        env:
          FOD_URL: ${{ vars.FOD_URL }}
          FOD_CLIENT_ID: ${{secrets.FOD_CLIENT_ID}}
          FOD_CLIENT_SECRET: ${{secrets.FOD_CLIENT_SECRET}}
          SETUP_EXTRA_OPTS: ${{ format('--sdlc-status Development --app-owner {0}', vars.FOD_DEFAULT_OWNER) }}
          PACKAGE_EXTRA_OPTS: -bt gradle -bf build.gradle -bc "clean build -x test"
          COPY_FROM_RELEASE: ${{ vars.FOD_DEFAULT_PARENT_RELEASE }}
          SAST_ASSESSMENT_TYPE: ${{ vars.FOD_DEFAULT_ASSESSMENT_TYPE }}
          DO_SETUP: true
          DO_SAST_SCAN: true
          DO_AVIATOR_AUDIT: true
          DO_SCA_SCAN: true
          DO_WAIT: true
          SAST_WAIT_EXTRA_OPTS: --timeout 3h
          DO_POLICY_CHECK: true
          DO_JOB_SUMMARY: true
          DO_PR_COMMENT: true
          DO_EXPORT: true

